### ISSUE TITLE
Typo on navigation bar

### ISSUE THREAD

**Issue by stevenbudinata** [AnkitSharmaOnGithub/covid19#3]
It's shown as "Date Visualization" on the navigation bar, I think it should be "Data Visualization". Can I fix this issue? Thank You

**Comment by AnkitSharmaOnGithub** [comment]
Yes. Go Ahead. Best of luck for Hacktoberfest. After fixing, Kindly create a PR.

**Comment by stevenbudinata** [comment]
Thank you
